import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StairAnimation from "./components/StairAnimation";
import NavigationBar from "./components/NavigationBar";
import FullScreenNav from "./components/FullScreenNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <NavigationBar/>
        <FullScreenNav/>
        <StairAnimation>
        {children}
        </StairAnimation>
        </body>
    </html>
  );
}
